# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alper Sarikaya
email: alper@datav.is
description: > # this means to ignore newlines until "baseurl:"
  The homepage for Alper Sarikaya, data visualizer.  Current and previous projects are detailed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alper.datav.is" # the base hostname & protocol for your site, e.g. http://example.com
authors: Alper Sarikaya
twitter_username: yelperalp
github_username:  yelper
social_image_path: /assets/img/face2.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
#  - jekyll-contentblocks

permalink: /blog/:year/:month/:title/

# add some custom collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/

  recipes:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: "recipes"


include: ['.htaccess', 'recipe_data.json']

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
